return {
    Spin1 = {
        ProductId = 3585711703,
        Reward = {
            Type = "Spins",
            Params = 1
        }
    },
    Spin10 = {
        ProductId = 3585711803,
        Reward = {
            Type = "Spins",
            Params = 10
        }
    },
    Spin100 = {
        ProductId = 3585711903,
        Reward = {
            Type = "Spins",
            Params = 100
        }
    },
}